export const EMPLOYEE_SKILL_LIST = "EMPLOYEE_SKILL_LIST";
export const EMPLOYEE_SKILL_NO_DATA = "EMPLOYEE_SKILL_NO_DATA";
export const EMPLOYEE_SKILL_ADD = "EMPLOYEE_SKILL_ADD";
export const EMPLOYEE_SKILL_EDIT = "EMPLOYEE_SKILL_EDIT";
export const EMPLOYEE_SKILL_UPDATE = "EMPLOYEE_SKILL_UPDATE";
export const EMPLOYEE_SKILL_DELETE = "EMPLOYEE_SKILL_DELETE";
export const EMPLOYEE_PROJECT_NAME = "EMPLOYEE_PROJECT_NAME";
