export const EMPLOYEE_LIST = 'EMPLOYEE_LIST';
export const EMPLOYEE_SKILL='EMPLOYEE_SKILL';
export const EMPLOYEE_NO_DATA = 'EMPLOYEE_NO_DATA';
export const EMPLOYEE_ADD = 'EMPLOYEE_ADD';
export const EMPLOYEE_EDIT = 'EMPLOYEE_EDIT';
export const EMPLOYEE_UPDATE = 'EMPLOYEE_UPDATE';
export const EMPLOYEE_DELETE = 'EMPLOYEE_DELETE';