export const PROJECT_SKILL_LIST = "PROJECT_SKILL_LIST";
export const PROJECT_SKILL_NO_DATA = "PROJECT_SKILL_NO_DATA";
export const PROJECT_SKILL_ADD = "PROJECT_SKILL_ADD";
export const PROJECT_SKILL_EDIT = "PROJECT_SKILL_EDIT";
export const PROJECT_SKILL_UPDATE = "PROJECT_SKILL_UPDATE";
export const PROJECT_SKILL_DELETE = "PROJECT_SKILL_DELETE";
